name = input("Введите ваше имя: ")
my_string = input("Как ваше настроение? ")
print("Здравствуйте, ", name)
print("Я очень рад, что ", my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])